Feature/fail dashboard
RagtagOpen/cta-scraper pull request #4
Opened 2017-08-07 05:04 UTC by bnd5k

This PR 
* Adds basic UI for a dashboard showing scraping failures
* Adds ability to see details about how scraping failed
* Allows for a soft delete of a scraping Failure.  I figure that once we see fix a scraping script gone awry, we'll want a way to make sure it doesn't appear again.
* Removes old generic Dashboard view (it was a placeholder)

Dashboard:

![image](https://user-images.githubusercontent.com/769888/29012742-bc5d21d2-7af2-11e7-999f-1e96c522e48d.png)

Detail:

![image](https://user-images.githubusercontent.com/769888/29012756-cce578d8-7af2-11e7-8894-5ff6a657dda3.png)

2017-08-07 17:00 UTC, UnderpantsGnome requested changes

2017-08-07 17:00 UTC, UnderpantsGnome commented on app/views/scrape_fails/index.html.erb
> +    Once you have fixed the cause of the scraping error, please dismiss the error.  This will perform a soft delete and he record won't appear below anymore.
typo `and he record`

2017-08-08 03:00 UTC, bnd5k commented
@UnderpantsGnome I fixed that typo and also added pagination to the ScrapeFail controller

2017-08-09 18:11 UTC, UnderpantsGnome approved these changes

2017-08-09 21:07 UTC, merged